# Generated by Django 4.1.4 on 2023-02-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera", models.CharField(default="now ip", max_length=50)),
                ("start_tracking", models.DateTimeField(default=None, max_length=50)),
                ("stop_tracking", models.DateTimeField(default=None, max_length=50)),
            ],
            options={
                "verbose_name": "IdleAction",
                "verbose_name_plural": "IdleActions",
            },
        ),
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=250)),
                (
                    "idle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="IdleControl.actions",
                    ),
                ),
            ],
            options={
                "verbose_name": "PhotoAction",
                "verbose_name_plural": "PhotoActions",
            },
        ),
    ]
