# Generated by Django 4.1.4 on 2023-02-17 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("IdleControl", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actions",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
