# Generated by Django 4.1.4 on 2023-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IdleControl", "0003_alter_actions_start_tracking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actions",
            name="camera",
            field=models.CharField(default="now ip", max_length=50),
        ),
        migrations.AlterField(
            model_name="actions",
            name="start_tracking",
            field=models.DateTimeField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="actions",
            name="stop_tracking",
            field=models.DateTimeField(default=None, max_length=50),
        ),
    ]
