# Generated by Django 4.1.4 on 2023-05-16 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("CameraAlgorithms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_tracking",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stop_tracking",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "violation_found",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("extra", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("false", "False"), ("true", "True")],
                        default="false",
                        max_length=30,
                    ),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CameraAlgorithms.algorithm",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CameraAlgorithms.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "report",
            },
        ),
        migrations.CreateModel(
            name="SkanyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skany_index",
                    models.IntegerField(null=True, verbose_name="skany index"),
                ),
                ("zlecenie", models.CharField(blank=True, max_length=50, null=True)),
                ("violation_found", models.BooleanField(blank=True, null=True)),
                ("execution_date", models.DateTimeField(blank=True, null=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Reports.report"
                    ),
                ),
            ],
            options={
                "verbose_name": "ReportSkany",
                "verbose_name_plural": "ReportsSkany",
                "db_table": "skany_report",
            },
        ),
    ]
