# Generated by Django 4.1.4 on 2023-03-24 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Algorithms", "0001_initial"),
        ("Cameras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_tracking",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "stop_tracking",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "violation_found",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("extra", models.JSONField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("false", "False"), ("true", "True")],
                        default="false",
                        max_length=30,
                    ),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Algorithms.algorithm",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Cameras.camera"
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
            },
        ),
    ]
