# Generated by Django 4.1.4 on 2023-05-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Algorithms", "0003_alter_cameraalgorithm_process_id"),
        ("Cameras", "0002_rename_password_camera__password"),
        ("Reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="algorithm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Algorithms.algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Cameras.camera"
            ),
        ),
        migrations.AlterField(
            model_name="skanyreport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Reports.report"
            ),
        ),
    ]
