# Generated by Django 4.1.4 on 2023-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[("false", "False"), ("true", "True")],
                default="false",
                max_length=30,
            ),
        ),
    ]
