# Generated by Django 4.1.4 on 2023-05-04 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Algorithms", "0003_alter_cameraalgorithm_process_id"),
        ("Cameras", "0003_rename__password_camera_password"),
        ("Reports", "0002_alter_report_algorithm_alter_report_camera_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="algorithm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Algorithms.algorithm"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Cameras.camera"
            ),
        ),
        migrations.AlterField(
            model_name="skanyreport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Reports.report"
            ),
        ),
    ]
