# Generated by Django 4.1.4 on 2023-05-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0003_rename__password_camera_password"),
        ("Reports", "0003_alter_report_algorithm_alter_report_camera_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="Cameras.camera"
            ),
        ),
    ]
