# Generated by Django 4.1.7 on 2023-06-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Reports", "0003_skanyreport_operation_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skanyreport",
            name="operation_time",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
