# Generated by Django 4.1.4 on 2023-05-11 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0003_rename__password_camera_password"),
        ("Reports", "0004_alter_report_camera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="camera",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Cameras.camera",
            ),
        ),
    ]
