# Generated by Django 4.2.1 on 2023-10-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Reports", "0005_rename_operation_time_skanyreport_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="start_tracking",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="stop_tracking",
            field=models.DateTimeField(null=True),
        ),
    ]
