# Generated by Django 4.1.4 on 2023-05-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Reports", "0005_alter_report_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="skanyreport",
            name="execution_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skanyreport",
            name="violation_found",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skanyreport",
            name="zlecenia_index",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="skanyreport",
            name="skany_index",
            field=models.IntegerField(null=True, verbose_name="skany index"),
        ),
    ]
