# Generated by Django 4.1.4 on 2023-05-11 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Reports", "0006_skanyreport_execution_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skanyreport",
            old_name="zlecenia_index",
            new_name="zlecenie",
        ),
    ]
