# Generated by Django 4.1.4 on 2023-05-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("CameraAlgorithms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=75, verbose_name="Item name")),
                ("status", models.CharField(default="Out of stock", max_length=20)),
                (
                    "current_stock_level",
                    models.IntegerField(default=0, verbose_name="Current stock level"),
                ),
                (
                    "low_stock_level",
                    models.IntegerField(default=0, verbose_name="Low stock level"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                ("coords", models.JSONField(verbose_name="Area coordinates")),
                (
                    "prev_status",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=30,
                        null=True,
                        verbose_name="Previous status",
                    ),
                ),
                (
                    "multi_row",
                    models.BooleanField(default=False, verbose_name="Multi row"),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camera_id",
                        to="CameraAlgorithms.camera",
                    ),
                ),
            ],
        ),
    ]
