# Generated by Django 4.1.4 on 2023-04-10 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="email",
        ),
    ]
