# Generated by Django 4.1.4 on 2023-03-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="coords",
            field=models.TextField(
                blank=True, null=True, verbose_name="Area coordinates"
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="date_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Date updated"),
        ),
        migrations.AlterField(
            model_name="items",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date created"),
        ),
    ]
