# Generated by Django 4.1.4 on 2023-04-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="coords",
            field=models.JSONField(
                default=[{"x1": 0, "x2": 0, "y1": 0, "y2": 0}],
                verbose_name="Area coordinates",
            ),
            preserve_default=False,
        ),
    ]
