# Generated by Django 4.1.4 on 2023-04-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0002_remove_items_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="prev_status",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Previous status",
            ),
        ),
    ]
