# Generated by Django 4.1.4 on 2023-06-02 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Suppliers", "0001_initial"),
        ("Inventory", "0002_alter_items_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="order_quantity",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Order quantity"
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="suppliers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Supplier",
                to="Suppliers.suppliers",
            ),
        ),
    ]
