# Generated by Django 4.1.4 on 2023-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0003_items_prev_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="multi_row",
            field=models.BooleanField(default=False, verbose_name="Multi row"),
        ),
    ]
