# Generated by Django 4.1.4 on 2023-05-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0004_items_multi_row"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="low_stock_level",
            field=models.IntegerField(default=0, verbose_name="Low stock level"),
        ),
    ]
