# Generated by Django 4.2.1 on 2023-06-20 10:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0005_items_copy_emails_items_subject_items_to_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="copy_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
                verbose_name="Copy_emails",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="to_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                blank=True,
                null=True,
                size=None,
                verbose_name="To_emails",
            ),
        ),
    ]
