# Generated by Django 4.2.1 on 2023-07-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0006_alter_items_copy_emails_alter_items_to_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="object_type",
            field=models.CharField(
                choices=[("bottle", "Bottle"), ("box", "Box")],
                default="box",
                max_length=20,
                verbose_name="Object type",
            ),
        ),
    ]
