# Generated by Django 4.2.1 on 2023-07-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0008_alter_items_object_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="multi_row",
        ),
        migrations.AlterField(
            model_name="items",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("bottles", "Bottles"),
                    ("boxes", "Boxes"),
                    ("red lines", "Red Lines"),
                ],
                default="boxes",
                max_length=20,
                verbose_name="Object type",
            ),
        ),
    ]
