# Generated by Django 4.2.1 on 2023-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Inventory", "0009_remove_items_multi_row_alter_items_object_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("bottles", "Bottles"),
                    ("boxes", "Boxes"),
                    ("red lines", "Red Lines"),
                ],
                max_length=20,
                verbose_name="Object type",
            ),
        ),
    ]
