# Generated by Django 4.1.4 on 2023-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MachineControl", "0002_alter_machineaction_start_tracking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machineaction",
            name="camera",
            field=models.CharField(default="now ip", max_length=50),
        ),
        migrations.AlterField(
            model_name="machineaction",
            name="photo_start",
            field=models.CharField(default="now photo", max_length=250),
        ),
        migrations.AlterField(
            model_name="machineaction",
            name="photo_stop",
            field=models.CharField(default="now photo", max_length=250),
        ),
        migrations.AlterField(
            model_name="machineaction",
            name="start_tracking",
            field=models.DateTimeField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="machineaction",
            name="stop_tracking",
            field=models.DateTimeField(default=None, max_length=50),
        ),
    ]
