# Generated by Django 4.2.1 on 2024-11-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="workplace",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="erp_5s.referenceitems",
            ),
        ),
    ]
