# Generated by Django 4.2.1 on 2024-11-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="workplace_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
