# Generated by Django 4.2.1 on 2024-12-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0002_customuser_workplace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="workplace",
        ),
        migrations.AddField(
            model_name="customuser",
            name="workplace_id",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
