# Generated by Django 4.2.1 on 2025-01-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0003_passwordresetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True, unique=True
            ),
        ),
    ]
