# Generated by Django 4.2.1 on 2025-01-28 13:50

from django.db import migrations, models
import uuid


def update_empty_emails(apps, schema_editor):
    CustomUser = apps.get_model('Employees', 'CustomUser')
    for user in CustomUser.objects.filter(email=''):
        user.email = f"{user.username}@example.com"
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0003_passwordresetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, null=True, unique=True
            ),
        ),
    ]
