# Generated by Django 4.2.1 on 2025-01-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, unique=True
            ),
        ),
    ]
