# Generated by Django 4.2.1 on 2025-02-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Employees", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="work_end_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="work_start_time",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
