# Generated by Django 4.2.1 on 2024-07-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManifestConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("token", models.CharField(blank=True, max_length=200)),
                ("status", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
