# Generated by Django 4.2.1 on 2024-07-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifest_api", "0002_alter_manifestconnection_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifestconnection",
            name="host",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="manifestconnection",
            name="id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="manifestconnection",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
