# Generated by Django 4.2.1 on 2024-07-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifest_api", "0003_alter_manifestconnection_host_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifestconnection",
            name="host",
            field=models.CharField(max_length=200),
        ),
    ]
