# Generated by Django 4.2.1 on 2024-07-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifest_api", "0004_alter_manifestconnection_host"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifestconnection",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="manifestconnection",
            name="last_updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
