# Generated by Django 4.2.1 on 2024-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifest_api", "0005_alter_manifestconnection_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifestconnection",
            name="password",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
