# Generated by Django 4.2.1 on 2024-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manifest_api", "0006_alter_manifestconnection_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="manifestconnection",
            name="asset_class_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manifestconnection",
            name="asset_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manifestconnection",
            name="assigned_user",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manifestconnection",
            name="job_template",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manifestconnection",
            name="location_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
