# Generated by Django 4.2.1 on 2024-09-11 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manifest_api", "0008_alter_manifestconnection_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManifestConnection",
        ),
    ]
