# Generated by Django 4.2.1 on 2024-01-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_post", models.TextField()),
                ("text_comment", models.TextField()),
                ("link_author_comment", models.URLField()),
                ("about", models.TextField()),
                ("about_author", models.TextField()),
                ("company", models.CharField(max_length=255)),
                ("experience", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("extension_user", models.CharField(max_length=255)),
                ("ai_comments", models.TextField()),
                ("project_id", models.CharField(max_length=50)),
            ],
        ),
    ]
