# Generated by Django 4.2.1 on 2024-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Extension", "0002_extensionreport_delete_socialpost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extensionreport",
            name="link_author_comment",
            field=models.URLField(blank=True, null=True),
        ),
    ]
