# Generated by Django 4.2.1 on 2024-01-31 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("Extension", "0004_alter_extensionreport_link_author_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extensionreport",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extensionreport",
            name="user_company",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
