# Generated by Django 4.1.4 on 2023-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skany",
            fields=[
                (
                    "indeks",
                    models.IntegerField(
                        db_column="Indeks", primary_key=True, serialize=False
                    ),
                ),
                (
                    "archiwum",
                    models.IntegerField(blank=True, db_column="Archiwum", null=True),
                ),
                ("data", models.DateTimeField(blank=True, db_column="Data", null=True)),
                (
                    "del_field",
                    models.IntegerField(blank=True, db_column="Del", null=True),
                ),
                (
                    "kodkreskowy",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="KodKreskowy",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "oscieznica",
                    models.IntegerField(blank=True, db_column="Oscieznica", null=True),
                ),
                (
                    "pozycja",
                    models.IntegerField(blank=True, db_column="Pozycja", null=True),
                ),
                (
                    "skrzydlo",
                    models.IntegerField(blank=True, db_column="Skrzydlo", null=True),
                ),
                ("srcdoc", models.IntegerField(blank=True, null=True)),
                (
                    "stanowisko",
                    models.IntegerField(blank=True, db_column="Stanowisko", null=True),
                ),
                (
                    "sztuka",
                    models.IntegerField(blank=True, db_column="Sztuka", null=True),
                ),
                (
                    "uzytkownik",
                    models.IntegerField(blank=True, db_column="Uzytkownik", null=True),
                ),
                (
                    "zakonczony",
                    models.IntegerField(blank=True, db_column="Zakonczony", null=True),
                ),
                (
                    "czynnosc",
                    models.IntegerField(blank=True, db_column="Czynnosc", null=True),
                ),
                (
                    "dbwhokna",
                    models.IntegerField(blank=True, db_column="DbWHOkna", null=True),
                ),
                (
                    "guid",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Guid",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "guidparent",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="GuidParent",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(blank=True, db_column="Status", null=True),
                ),
                ("typ", models.IntegerField(blank=True, db_column="Typ", null=True)),
                (
                    "typslupka",
                    models.IntegerField(blank=True, db_column="TypSlupka", null=True),
                ),
                (
                    "erridx",
                    models.IntegerField(blank=True, db_column="ErrIdx", null=True),
                ),
            ],
            options={
                "db_table": "Skany",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SkanyVsZlecenia",
            fields=[
                (
                    "indeks",
                    models.IntegerField(
                        db_column="Indeks", primary_key=True, serialize=False
                    ),
                ),
                (
                    "indeksskanu",
                    models.IntegerField(blank=True, db_column="IndeksSkanu", null=True),
                ),
                (
                    "indekszlecenia",
                    models.IntegerField(
                        blank=True, db_column="IndeksZlecenia", null=True
                    ),
                ),
                (
                    "indeksdodatka",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="IndeksDodatka",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "duplicated",
                    models.IntegerField(blank=True, db_column="Duplicated", null=True),
                ),
            ],
            options={
                "db_table": "Skany_vs_Zlecenia",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stanowiska",
            fields=[
                (
                    "indeks",
                    models.IntegerField(
                        db_column="Indeks", primary_key=True, serialize=False
                    ),
                ),
                (
                    "aktywny",
                    models.IntegerField(blank=True, db_column="Aktywny", null=True),
                ),
                ("data", models.DateTimeField(blank=True, db_column="Data", null=True)),
                (
                    "del_field",
                    models.IntegerField(blank=True, db_column="Del", null=True),
                ),
                (
                    "drukujraport",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="DrukujRaport",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "liczbaporzadkowa",
                    models.IntegerField(
                        blank=True, db_column="LiczbaPorzadkowa", null=True
                    ),
                ),
                (
                    "liniaprodukcyjna",
                    models.IntegerField(
                        blank=True, db_column="LiniaProdukcyjna", null=True
                    ),
                ),
                (
                    "obslugastojakow",
                    models.IntegerField(
                        blank=True, db_column="ObslugaStojakow", null=True
                    ),
                ),
                (
                    "opis",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Opis",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "opisczynnosci",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="OpisCzynnosci",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "podstatusprzed",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="PodstatusPrzed",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "podstatuspo",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="PodstatusPo",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "raport",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Raport",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "raportdodatki",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="RaportDodatki",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "rozwintabelke",
                    models.IntegerField(
                        blank=True, db_column="RozwinTabelke", null=True
                    ),
                ),
                (
                    "skanowanie",
                    models.IntegerField(blank=True, db_column="Skanowanie", null=True),
                ),
                (
                    "stanowiskokoncowe",
                    models.IntegerField(
                        blank=True, db_column="StanowiskoKoncowe", null=True
                    ),
                ),
                (
                    "wielkoscczcionki",
                    models.IntegerField(
                        blank=True, db_column="WielkoscCzcionki", null=True
                    ),
                ),
                (
                    "zdejmowanie",
                    models.IntegerField(blank=True, db_column="Zdejmowanie", null=True),
                ),
                (
                    "zliczanie",
                    models.IntegerField(blank=True, db_column="Zliczanie", null=True),
                ),
                (
                    "zoom1",
                    models.IntegerField(blank=True, db_column="Zoom1", null=True),
                ),
                (
                    "zoom2",
                    models.IntegerField(blank=True, db_column="Zoom2", null=True),
                ),
                (
                    "proceduraskladowa",
                    models.IntegerField(
                        blank=True, db_column="ProceduraSkladowa", null=True
                    ),
                ),
                (
                    "viewer",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Viewer",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "czynnoscosc",
                    models.IntegerField(blank=True, db_column="CzynnoscOsc", null=True),
                ),
                (
                    "czynnoscskr",
                    models.IntegerField(blank=True, db_column="CzynnoscSkr", null=True),
                ),
                (
                    "czynnoscslr",
                    models.IntegerField(blank=True, db_column="CzynnoscSlr", null=True),
                ),
                (
                    "czynnoscsls",
                    models.IntegerField(blank=True, db_column="CzynnoscSls", null=True),
                ),
                (
                    "czynnoscszkl",
                    models.IntegerField(
                        blank=True, db_column="CzynnoscSzkl", null=True
                    ),
                ),
                (
                    "obslugatransportu",
                    models.IntegerField(
                        blank=True, db_column="ObslugaTransportu", null=True
                    ),
                ),
                (
                    "barcodeidx",
                    models.IntegerField(blank=True, db_column="BarcodeIdx", null=True),
                ),
                (
                    "barcodeprevidx",
                    models.IntegerField(
                        blank=True, db_column="BarcodePrevIdx", null=True
                    ),
                ),
                (
                    "barcodenextidx",
                    models.IntegerField(
                        blank=True, db_column="BarcodeNextIdx", null=True
                    ),
                ),
                (
                    "cursortimeout",
                    models.IntegerField(
                        blank=True, db_column="CursorTimeout", null=True
                    ),
                ),
                (
                    "defaultevent",
                    models.IntegerField(
                        blank=True, db_column="DefaultEvent", null=True
                    ),
                ),
                (
                    "tablefilter",
                    models.IntegerField(blank=True, db_column="TableFilter", null=True),
                ),
                (
                    "panelinfowidth",
                    models.IntegerField(
                        blank=True, db_column="PanelInfoWidth", null=True
                    ),
                ),
                (
                    "printer",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Printer",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "raportstojaki",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="RaportStojaki",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "zoomstands",
                    models.IntegerField(blank=True, db_column="ZoomStands", null=True),
                ),
                (
                    "middle",
                    models.IntegerField(blank=True, db_column="Middle", null=True),
                ),
                (
                    "middle_type",
                    models.IntegerField(blank=True, db_column="Middle_type", null=True),
                ),
                (
                    "obslugasektorow",
                    models.IntegerField(
                        blank=True, db_column="ObslugaSektorow", null=True
                    ),
                ),
                (
                    "userdescription",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="UserDescription",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "userstatus",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="UserStatus",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "canhavedifferentip",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="CanHaveDifferentIP",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "qualitycontrolworkplace",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="QualityControlWorkplace",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "alvarchar",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="AlVARCHAR",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "altextrasworkplace",
                    models.IntegerField(
                        blank=True, db_column="AlTEXTrasWorkplace", null=True
                    ),
                ),
                (
                    "allowglassscan",
                    models.IntegerField(
                        blank=True, db_column="AllowGlassScan", null=True
                    ),
                ),
                (
                    "onlyoneworkeronthisworkplace",
                    models.IntegerField(
                        blank=True, db_column="OnlyOneWorkerOnThisWorkplace", null=True
                    ),
                ),
                (
                    "altextrasdatecolumnname",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="AlTEXTrasDateColumnName",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "hidelaborbutton",
                    models.IntegerField(
                        blank=True, db_column="HideLaborButton", null=True
                    ),
                ),
                (
                    "importpackagestoszybyxls",
                    models.IntegerField(
                        blank=True, db_column="ImportPackagesToSzybyXLS", null=True
                    ),
                ),
                (
                    "hidetableinpackagesloading",
                    models.IntegerField(
                        blank=True, db_column="HideTableInPackagesLoading", null=True
                    ),
                ),
                (
                    "altcuttingworkplace",
                    models.IntegerField(
                        blank=True, db_column="AltCuttingWorkplace", null=True
                    ),
                ),
                (
                    "mobile",
                    models.IntegerField(blank=True, db_column="Mobile", null=True),
                ),
                (
                    "markwhentransportispacked",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "Stanowiska",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Uzytkownicy",
            fields=[
                (
                    "indeks",
                    models.IntegerField(
                        db_column="Indeks", primary_key=True, serialize=False
                    ),
                ),
                (
                    "aktywny",
                    models.IntegerField(blank=True, db_column="Aktywny", null=True),
                ),
                ("data", models.DateTimeField(blank=True, db_column="Data", null=True)),
                (
                    "dealer",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Dealer",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "del_field",
                    models.IntegerField(blank=True, db_column="Del", null=True),
                ),
                (
                    "haslo",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Haslo",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "imie",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Imie",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "login",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Login",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "nazwa",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Nazwa",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "nazwisko",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Nazwisko",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "nip",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Nip",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "uprawnienia",
                    models.IntegerField(blank=True, db_column="Uprawnienia", null=True),
                ),
                ("usr", models.IntegerField(blank=True, db_column="Usr", null=True)),
                (
                    "uwagi",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Uwagi",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "stawkadzienna",
                    models.IntegerField(
                        blank=True, db_column="StawkaDzienna", null=True
                    ),
                ),
                (
                    "barcodeidx",
                    models.IntegerField(blank=True, db_column="BarcodeIdx", null=True),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Language",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "grupaplacowa",
                    models.IntegerField(
                        blank=True, db_column="GrupaPlacowa", null=True
                    ),
                ),
                (
                    "tworzenieartykulow",
                    models.IntegerField(
                        blank=True, db_column="TworzenieArtykulow", null=True
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Email",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "zestawieniezlecennaprodukcjivisible",
                    models.IntegerField(
                        blank=True,
                        db_column="ZestawienieZlecenNaProdukcjiVisible",
                        null=True,
                    ),
                ),
                (
                    "zawartoscstojakowvisible",
                    models.IntegerField(
                        blank=True, db_column="ZawartoscStojakowVisible", null=True
                    ),
                ),
                (
                    "zawartoscsamochodowvisible",
                    models.IntegerField(
                        blank=True, db_column="ZawartoscSamochodowVisible", null=True
                    ),
                ),
                (
                    "zawartoscsektorowvisible",
                    models.IntegerField(
                        blank=True, db_column="ZawartoscSektorowVisible", null=True
                    ),
                ),
                (
                    "zawartoscsektorowszkleniavisible",
                    models.IntegerField(
                        blank=True,
                        db_column="ZawartoscSektorowSzkleniaVisible",
                        null=True,
                    ),
                ),
                (
                    "zestawienieczynnoscivisible",
                    models.IntegerField(
                        blank=True, db_column="ZestawienieCzynnosciVisible", null=True
                    ),
                ),
                (
                    "zestawienieodpowiedzinapytaniavisible",
                    models.IntegerField(
                        blank=True,
                        db_column="ZestawienieOdpowiedziNaPytaniaVisible",
                        null=True,
                    ),
                ),
                (
                    "zestawienierobociznyvisible",
                    models.IntegerField(
                        blank=True, db_column="ZestawienieRobociznyVisible", null=True
                    ),
                ),
                (
                    "zestawieniebledowkomunikatownotatekvisible",
                    models.IntegerField(
                        blank=True,
                        db_column="ZestawienieBledowKomunikatowNotatekVisible",
                        null=True,
                    ),
                ),
                (
                    "eksportwykonanychoscieznicvisible",
                    models.IntegerField(
                        blank=True,
                        db_column="EksportWykonanychOscieznicVisible",
                        null=True,
                    ),
                ),
                (
                    "posteprealizacjivisible",
                    models.IntegerField(
                        blank=True, db_column="PostepRealizacjiVisible", null=True
                    ),
                ),
                (
                    "dodajpracownikavisible",
                    models.IntegerField(
                        blank=True, db_column="DodajPracownikaVisible", null=True
                    ),
                ),
                (
                    "cofnijskanvisible",
                    models.IntegerField(
                        blank=True, db_column="CofnijSkanVisible", null=True
                    ),
                ),
                (
                    "zestawienieczynnoscinewvisible",
                    models.IntegerField(
                        blank=True,
                        db_column="ZestawienieCzynnosciNewVisible",
                        null=True,
                    ),
                ),
                (
                    "visibilitylastdatechange",
                    models.DateTimeField(
                        blank=True, db_column="VisibilityLastDateChange", null=True
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Image",
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Uzytkownicy",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Zlecenia",
            fields=[
                (
                    "indeks",
                    models.IntegerField(
                        db_column="Indeks", primary_key=True, serialize=False
                    ),
                ),
                (
                    "archiwum",
                    models.IntegerField(blank=True, db_column="Archiwum", null=True),
                ),
                ("data", models.DateTimeField(blank=True, db_column="Data", null=True)),
                (
                    "datawejscia",
                    models.DateTimeField(
                        blank=True, db_column="DataWejscia", null=True
                    ),
                ),
                (
                    "datazakonczenia",
                    models.DateTimeField(
                        blank=True, db_column="DataZakonczenia", null=True
                    ),
                ),
                (
                    "del_field",
                    models.IntegerField(blank=True, db_column="Del", null=True),
                ),
                (
                    "diler",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Diler",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "firststanowisko",
                    models.IntegerField(
                        blank=True, db_column="FirstStanowisko", null=True
                    ),
                ),
                (
                    "hiden",
                    models.IntegerField(blank=True, db_column="Hiden", null=True),
                ),
                (
                    "erridx",
                    models.IntegerField(blank=True, db_column="ErrIdx", null=True),
                ),
                (
                    "klient",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Klient",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "liczbaszklen",
                    models.IntegerField(
                        blank=True, db_column="LiczbaSzklen", null=True
                    ),
                ),
                (
                    "nipdilera",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="NipDilera",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "oscieznica",
                    models.IntegerField(blank=True, db_column="Oscieznica", null=True),
                ),
                (
                    "pozycja",
                    models.IntegerField(blank=True, db_column="Pozycja", null=True),
                ),
                (
                    "skanowanie",
                    models.IntegerField(blank=True, db_column="Skanowanie", null=True),
                ),
                (
                    "skrzydlo",
                    models.IntegerField(blank=True, db_column="Skrzydlo", null=True),
                ),
                ("srcdoc", models.IntegerField(blank=True, null=True)),
                (
                    "stanowisko",
                    models.IntegerField(blank=True, db_column="Stanowisko", null=True),
                ),
                (
                    "stanowiskopoprzednie",
                    models.IntegerField(
                        blank=True, db_column="StanowiskoPoprzednie", null=True
                    ),
                ),
                (
                    "sztuka",
                    models.IntegerField(blank=True, db_column="Sztuka", null=True),
                ),
                (
                    "terminrealizacji",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="TerminRealizacji",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "zakonczone",
                    models.IntegerField(blank=True, db_column="Zakonczone", null=True),
                ),
                (
                    "zlecenie",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Zlecenie",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "zleceniedilera",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="ZlecenieDilera",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "dodopis",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="DodOpis",
                        max_length=250,
                        null=True,
                    ),
                ),
                ("optym", models.IntegerField(blank=True, null=True)),
                (
                    "terminprodukcji",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="TerminProdukcji",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "optymalizacja",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Optymalizacja",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "dbwhokna",
                    models.IntegerField(blank=True, db_column="DbWHOkna", null=True),
                ),
                (
                    "kodbiura",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="KodBiura",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "optsrcdoc",
                    models.IntegerField(blank=True, db_column="OptSrcdoc", null=True),
                ),
                ("vip", models.IntegerField(blank=True, db_column="Vip", null=True)),
                (
                    "obrazekosc",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="ObrazekOsc",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "obrazekskr",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="ObrazekSkr",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "referencja",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Referencja",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "priorytet",
                    models.IntegerField(blank=True, db_column="Priorytet", null=True),
                ),
                (
                    "iloscjedn",
                    models.FloatField(blank=True, db_column="IloscJedn", null=True),
                ),
                (
                    "idx_typu",
                    models.IntegerField(blank=True, db_column="Idx_typu", null=True),
                ),
                (
                    "typ",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Typ",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "iloscjednpoz",
                    models.FloatField(blank=True, db_column="IloscJednPoz", null=True),
                ),
                (
                    "pozycjalp",
                    models.IntegerField(blank=True, db_column="PozycjaLp", null=True),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Country",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "framewidth",
                    models.IntegerField(blank=True, db_column="FrameWidth", null=True),
                ),
                (
                    "frameheight",
                    models.IntegerField(blank=True, db_column="FrameHeight", null=True),
                ),
                (
                    "sashwidth",
                    models.IntegerField(blank=True, db_column="SashWidth", null=True),
                ),
                (
                    "sashheight",
                    models.IntegerField(blank=True, db_column="SashHeight", null=True),
                ),
                (
                    "glazing",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Glazing",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "glazingframe",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="GlazingFrame",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "glazingframecolor",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="GlazingFrameColor",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Color",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "paczka",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="Paczka",
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Zlecenia",
                "managed": False,
            },
        ),
    ]
