# Generated by Django 4.1.4 on 2023-04-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0001_initial"),
        ("OrderView", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexoperations",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Cameras.camera",
                unique=True,
                verbose_name="operations_control camera",
            ),
        ),
    ]
