# Generated by Django 4.1.7 on 2023-06-06 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("OrderView", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="indexoperations",
            options={
                "verbose_name": "IndexOperatio",
                "verbose_name_plural": "IndexOperations",
            },
        ),
        migrations.AlterModelTable(
            name="indexoperations",
            table="index_operations",
        ),
    ]
