# Generated by Django 4.1.4 on 2023-04-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0001_initial"),
        ("OrderView", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexoperations",
            name="camera",
            field=models.ForeignKey(
                default="192.168.1.163",
                on_delete=django.db.models.deletion.CASCADE,
                to="Cameras.camera",
                verbose_name="operations_control camera",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="indexoperations",
            name="type_operation",
            field=models.IntegerField(verbose_name="id_stanovisko operation control"),
        ),
    ]
