# Generated by Django 4.2.1 on 2023-06-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0004_zonecameras_index_workplace_zonecameras_workplace"),
        ("OrderView", "0002_alter_indexoperations_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexoperations",
            name="camera",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="CameraAlgorithms.camera",
                verbose_name="operations_control_camera",
            ),
        ),
        migrations.AlterField(
            model_name="indexoperations",
            name="type_operation",
            field=models.IntegerField(verbose_name="id_stanowisko_operation_control"),
        ),
    ]
