# Generated by Django 4.1.4 on 2023-03-23 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("OrderView", "0002_databaseconnection_delete_skany_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DatabaseConnection",
        ),
    ]
