# Generated by Django 4.1.4 on 2023-05-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0001_initial"),
        ("OrderView", "0003_alter_indexoperations_camera"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexoperations",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Cameras.camera",
                verbose_name="operations_control camera",
            ),
        ),
    ]
