# Generated by Django 4.1.4 on 2023-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatabaseConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("database_type", models.CharField(default="OrderView", max_length=50)),
                ("server", models.CharField(max_length=20)),
                ("database", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
    ]
