# Generated by Django 4.1.4 on 2023-04-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MsSqlConnector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseconnection",
            name="server",
            field=models.CharField(max_length=300),
        ),
    ]
