# Generated by Django 4.1.4 on 2023-04-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MsSqlConnector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaseconnection",
            name="port",
            field=models.IntegerField(default=1433),
        ),
    ]
