# Generated by Django 4.1.4 on 2023-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MsSqlConnector", "0002_alter_databaseconnection_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="databaseconnection",
            name="password",
        ),
        migrations.AddField(
            model_name="databaseconnection",
            name="password_encrypted",
            field=models.BinaryField(),
            preserve_default=False,
        ),
    ]
