# Generated by Django 4.1.4 on 2023-02-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.TextField(verbose_name="Image action")),
                ("action", models.TextField(verbose_name="Action")),
                (
                    "name_file",
                    models.TextField(
                        blank=True, null=True, verbose_name="Name pickle file"
                    ),
                ),
                ("camera", models.TextField(verbose_name="Camera")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Action",
                "verbose_name_plural": "Actions",
            },
        ),
    ]
