# Generated by Django 4.1.4 on 2023-02-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="Unknown", max_length=40, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="Unknown", max_length=40, null=True
                    ),
                ),
                (
                    "dataset",
                    models.TextField(
                        blank=True, null=True, verbose_name="Date Set user"
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="photo below"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="photo from above",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="photo in the center",
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="photo on the left",
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="photo on the right",
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False, verbose_name="Status in location"
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="Locations.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employers",
            },
        ),
    ]
