# Generated by Django 4.2.1 on 2024-12-06 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("erp_5s", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="items",
            table='"erp"."items"',
        ),
        migrations.AlterModelTable(
            name="operations",
            table='"erp"."operations"',
        ),
        migrations.AlterModelTable(
            name="orderitems",
            table='"erp"."order_items"',
        ),
        migrations.AlterModelTable(
            name="orderoperationdynamicinfo",
            table='"erp"."order_operation_dynamic_info"',
        ),
        migrations.AlterModelTable(
            name="orderoperations",
            table='"erp"."order_operations"',
        ),
        migrations.AlterModelTable(
            name="orderoperationtimespan",
            table='"erp"."order_operation_timespan"',
        ),
        migrations.AlterModelTable(
            name="orders",
            table='"erp"."orders"',
        ),
        migrations.AlterModelTable(
            name="referenceitems",
            table='"erp"."reference_items"',
        ),
        migrations.AlterModelTable(
            name="references",
            table='"erp"."references"',
        ),
    ]
