# Generated by Django 4.1.4 on 2023-02-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Safety", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="action",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
