# Generated by Django 4.1.4 on 2023-06-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_company",
                    models.TextField(verbose_name="Name of company suppliers"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="City of company suppliers",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="State of company suppliers",
                    ),
                ),
                ("website", models.TextField(verbose_name="Website of suppliers")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Contact email suppliers",
                    ),
                ),
                (
                    "contact_phone",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Contact phone number suppliers",
                    ),
                ),
                (
                    "contact_mobile_phone",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Contact mobile phone number suppliers",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Logo company"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="File to send notification",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date joined"),
                ),
                (
                    "date_edited",
                    models.DateTimeField(auto_now=True, verbose_name="Date edited"),
                ),
            ],
        ),
    ]
