# Generated by Django 4.2.1 on 2023-06-08 09:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("Suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliers",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Country of company suppliers",
            ),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="first_address",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lega address of company supplier",
            ),
        ),
        migrations.AddField(
            model_name="suppliers",
            name="second_address",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Physical address of company supplier",
            ),
        ),
    ]
