# Generated by Django 4.2.1 on 2023-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Suppliers", "0003_alter_suppliers_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliers",
            name="index",
            field=models.IntegerField(blank=True, null=True, verbose_name="Postcode"),
        ),
    ]
