# Generated by Django 4.2.1 on 2024-10-17 12:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_company", models.TextField(verbose_name="Name of my company")),
                (
                    "first_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Lega address of my company",
                    ),
                ),
                (
                    "second_address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Physical address of my company",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        max_length=2,
                        null=True,
                        verbose_name="Country of my company",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="State of my company",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="City of my company",
                    ),
                ),
                (
                    "website",
                    models.TextField(
                        blank=True, null=True, verbose_name="Website of suppliers"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        max_length=254, verbose_name="Contact email suppliers"
                    ),
                ),
                (
                    "contact_phone",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Contact phone number suppliers",
                    ),
                ),
                (
                    "contact_mobile_phone",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Contact mobile phone suppliers",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Logo suppliers",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="File to send notification",
                    ),
                ),
                (
                    "index",
                    models.IntegerField(blank=True, null=True, verbose_name="Postcode"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date joined"),
                ),
                (
                    "date_edited",
                    models.DateTimeField(auto_now=True, verbose_name="Date edited"),
                ),
                ("my_company", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "company",
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_key", models.TextField(verbose_name="Company license key")),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date joined"),
                ),
                (
                    "date_edited",
                    models.DateTimeField(auto_now=True, verbose_name="Date edited"),
                ),
                (
                    "valid_until",
                    models.DateField(verbose_name="Date which license is active"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Is active license"
                    ),
                ),
                (
                    "count_cameras",
                    models.IntegerField(verbose_name="Count of cameras in active"),
                ),
                (
                    "neurons_active",
                    models.IntegerField(verbose_name="Count of active neurons"),
                ),
            ],
            options={
                "verbose_name": "License",
                "verbose_name_plural": "Licenses",
                "db_table": "license",
            },
        ),
    ]
