# Generated by Django 4.1.4 on 2023-06-01 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CompanyLicense", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Company",
            new_name="License",
        ),
    ]
