# Generated by Django 4.2.1 on 2023-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CompanyLicense", "0002_license_alter_company_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="address_company",
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="City of company suppliers",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="contact_mobile_phone",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Contact mobile phone number suppliers",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="",
                verbose_name="File to send notification",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Logo company"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="State of company suppliers",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.TextField(
                blank=True, null=True, verbose_name="Website of suppliers"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Contact email suppliers",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_phone",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contact phone number suppliers"
            ),
        ),
    ]
