# Generated by Django 4.1.4 on 2023-06-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CompanyLicense", "0002_rename_company_license"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_company", models.TextField(verbose_name="Name of company")),
                (
                    "address_company",
                    models.TextField(verbose_name="Address of company"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="Contact email"),
                ),
                (
                    "contact_phone",
                    models.TextField(verbose_name="Contact phone number"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date joined"),
                ),
                (
                    "date_edited",
                    models.DateTimeField(auto_now=True, verbose_name="Date edited"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="license",
            name="name_company",
        ),
    ]
