# Generated by Django 4.2.1 on 2023-06-09 10:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("CompanyLicense", "0003_remove_company_address_company_company_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Country of my company",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="first_address",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lega address of my company",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="index",
            field=models.IntegerField(blank=True, null=True, verbose_name="Postcode"),
        ),
        migrations.AddField(
            model_name="company",
            name="second_address",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Physical address of my company",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="City of my company"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_email",
            field=models.EmailField(
                default=None, max_length=254, verbose_name="Contact email suppliers"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_mobile_phone",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contact mobile phone suppliers"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Logo suppliers"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name_company",
            field=models.TextField(verbose_name="Name of my company"),
        ),
        migrations.AlterField(
            model_name="company",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="State of my company"
            ),
        ),
    ]
