# Generated by Django 4.1.4 on 2023-06-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CompanyLicense", "0003_company_remove_license_name_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address_company",
            field=models.TextField(
                blank=True, null=True, verbose_name="Address of company"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contact email"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_phone",
            field=models.TextField(
                blank=True, null=True, verbose_name="Contact phone number"
            ),
        ),
    ]
