# Generated by Django 4.2.1 on 2023-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "CompanyLicense",
            "0004_company_country_company_first_address_company_index_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="my_company",
            field=models.BooleanField(default=False),
        ),
    ]
