# Generated by Django 4.2.1 on 2023-06-13 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CompanyLicense", "0005_company_my_company"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="company",
            table="company",
        ),
        migrations.AlterModelTable(
            name="license",
            table="license",
        ),
    ]
