# Generated by Django 4.1.4 on 2023-05-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ImageReport", "0001_initial"),
        ("Reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="report_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="Reports.report",
            ),
        ),
    ]
