# Generated by Django 4.2.1 on 2024-09-11 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ImageReport", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="image",
            table="images_reports",
        ),
    ]
