# Generated by Django 4.2.1 on 2024-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DayOfWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Day of week",
                "verbose_name_plural": "Day of week",
                "db_table": "days_of_week",
            },
        ),
        migrations.CreateModel(
            name="Emails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email to send notifications"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is activ email"),
                ),
            ],
            options={
                "verbose_name": "Emails",
                "verbose_name_plural": "Emails",
                "db_table": "emails",
            },
        ),
        migrations.CreateModel(
            name="SMTPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email_use_tls", models.BooleanField(default=False)),
                ("email_use_ssl", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "SMTP settings",
                "verbose_name_plural": "SMTP settings",
                "db_table": "smtp_settings",
            },
        ),
        migrations.CreateModel(
            name="WorkingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_start", models.TimeField(verbose_name="Start time")),
                ("time_end", models.TimeField(verbose_name="End time")),
                (
                    "days_of_week",
                    models.ManyToManyField(blank=True, to="Mailer.dayofweek"),
                ),
            ],
            options={
                "verbose_name": "Working time",
                "verbose_name_plural": "Working time",
                "db_table": "working_time",
            },
        ),
    ]
