# Generated by Django 4.1.4 on 2023-04-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SMTPSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server", models.CharField(max_length=255)),
                ("port", models.IntegerField()),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("email_use_tls", models.BooleanField(default=False)),
                ("email_use_ssl", models.BooleanField(default=True)),
            ],
        ),
    ]
