# Generated by Django 4.2.1 on 2025-02-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingTimeDaysOfWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Mailer.dayofweek",
                    ),
                ),
                (
                    "working_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Mailer.workingtime",
                    ),
                ),
            ],
            options={
                "verbose_name": "Working time days of week",
                "verbose_name_plural": "Working time day of week",
                "db_table": "working_time_days_of_week",
            },
        ),
        migrations.AlterField(
            model_name="workingtime",
            name="days_of_week",
            field=models.ManyToManyField(
                blank=True,
                through="Mailer.WorkingTimeDaysOfWeek",
                to="Mailer.dayofweek",
            ),
        ),
    ]
