# Generated by Django 4.2.1 on 2023-10-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0002_dayofweek"),
    ]

    operations = [
        migrations.AddField(
            model_name="workingtime",
            name="days_of_week",
            field=models.ManyToManyField(to="Mailer.dayofweek"),
        ),
    ]
