# Generated by Django 4.1.4 on 2023-04-11 12:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0002_emails_messages_recipients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messages",
            name="is_send",
        ),
    ]
