# Generated by Django 4.2.1 on 2025-02-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0002_workingtimedaysofweek_alter_workingtime_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingtimedaysofweek",
            name="day_of_week",
            field=models.ForeignKey(
                db_column="dayofweek_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="Mailer.dayofweek",
            ),
        ),
        migrations.AlterField(
            model_name="workingtimedaysofweek",
            name="working_time",
            field=models.ForeignKey(
                db_column="workingtime_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="Mailer.workingtime",
            ),
        ),
    ]
