# Generated by Django 4.2.1 on 2023-10-26 09:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0003_workingtime_days_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workingtime",
            name="days_of_week",
            field=models.ManyToManyField(
                default=django.db.models.manager.BaseManager.all, to="Mailer.dayofweek"
            ),
        ),
    ]
