# Generated by Django 4.1.4 on 2023-04-14 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0004_notificationssent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationssent",
            name="recipients",
        ),
        migrations.RemoveField(
            model_name="recipients",
            name="email",
        ),
        migrations.RemoveField(
            model_name="recipients",
            name="item",
        ),
        migrations.RemoveField(
            model_name="recipients",
            name="message",
        ),
        migrations.DeleteModel(
            name="Messages",
        ),
        migrations.DeleteModel(
            name="NotificationsSent",
        ),
        migrations.DeleteModel(
            name="Recipients",
        ),
    ]
