# Generated by Django 4.1.4 on 2023-04-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0005_remove_notificationssent_recipients_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_start", models.TimeField(verbose_name="Start time")),
                ("time_end", models.TimeField(verbose_name="End time")),
            ],
        ),
    ]
