# Generated by Django 4.2.1 on 2024-09-11 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0006_alter_workingtime_days_of_week"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayofweek",
            options={
                "verbose_name": "Day of week",
                "verbose_name_plural": "Day of week",
            },
        ),
        migrations.AlterModelOptions(
            name="emails",
            options={"verbose_name": "Emails", "verbose_name_plural": "Emails"},
        ),
        migrations.AlterModelOptions(
            name="smtpsettings",
            options={
                "verbose_name": "SMTP settings",
                "verbose_name_plural": "SMTP settings",
            },
        ),
        migrations.AlterModelOptions(
            name="workingtime",
            options={
                "verbose_name": "Working time",
                "verbose_name_plural": "Working time",
            },
        ),
        migrations.AlterModelTable(
            name="dayofweek",
            table="days_of_week",
        ),
        migrations.AlterModelTable(
            name="emails",
            table="emails",
        ),
        migrations.AlterModelTable(
            name="smtpsettings",
            table="smtp_settings",
        ),
        migrations.AlterModelTable(
            name="workingtime",
            table="working_time",
        ),
    ]
