# Generated by Django 4.1.4 on 2023-04-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0006_workingtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="emails",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Email"),
        ),
    ]
