# Generated by Django 4.1.4 on 2023-04-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0007_emails_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emails",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is activ email"),
        ),
    ]
