# Generated by Django 4.2.1 on 2023-08-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmessage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="systemmessage",
            name="id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
