# Generated by Django 4.2.1 on 2024-09-11 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0002_alter_systemmessage_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemmessage",
            options={
                "verbose_name": "System message",
                "verbose_name_plural": "System message",
            },
        ),
        migrations.AlterModelTable(
            name="systemmessage",
            table="system_message",
        ),
    ]
