# Generated by Django 4.2.1 on ...

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Core', '0002_custompermission'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE auth_group_permissions ADD COLUMN custom_permission_id INTEGER NULL REFERENCES auth_permission_custom(id)',
            reverse_sql='ALTER TABLE auth_group_permissions DROP COLUMN custom_permission_id',
        ),
    ]
