# Generated by Django 4.2.1 on ...

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_add_custom_permission_id_to_auth_group_permissions'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE auth_group_permissions RENAME COLUMN custom_permission_id TO permission_custom_id',
            reverse_sql='ALTER TABLE auth_group_permissions RENAME COLUMN permission_custom_id TO custom_permission_id',
        ),
    ]
