# Generated by Django 4.2.1 on ...

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_rename_custom_permission_id_to_permission_custom_id'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE auth_group_permissions ALTER COLUMN permission_id DROP NOT NULL',
            reverse_sql='ALTER TABLE auth_group_permissions ALTER COLUMN permission_id SET NOT NULL',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE auth_group_permissions ALTER COLUMN permission_custom_id DROP NOT NULL',
            reverse_sql='ALTER TABLE auth_group_permissions ALTER COLUMN permission_custom_id SET NOT NULL',
        ),
    ]
