# Generated by Django 4.2.1 on 2024-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConnectionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "erp_system",
                    models.CharField(
                        choices=[
                            ("odoo", "ODOO"),
                            ("winkhaus", "Winkhaus"),
                            ("manifest", "Manifest"),
                            ("5s_control", "5sControl"),
                        ],
                        default="winkhaus",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("database", "Database"), ("api", "API")],
                        default="database",
                        max_length=10,
                    ),
                ),
                (
                    "dbms",
                    models.CharField(
                        choices=[
                            ("postgres", "PostgreSQL"),
                            ("mssql", "Microsoft SQL Server"),
                            ("manifest", "Manifest"),
                        ],
                        default="mssql",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("host", models.CharField(blank=True, max_length=250, null=True)),
                ("server", models.CharField(blank=True, max_length=200, null=True)),
                ("database", models.CharField(blank=True, max_length=200, null=True)),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(blank=True, max_length=500, null=True)),
                ("port", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Connection Info",
                "verbose_name_plural": "Connection Infos",
                "db_table": "connection_info",
            },
        ),
    ]
