# Generated by Django 4.2.1 on 2023-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DatabaseConnections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="databaseconnection",
            name="dbms",
            field=models.CharField(
                choices=[("postgres", "PostgreSQL"), ("mssql", "Microsoft SQL Server")],
                default="mssql",
                max_length=50,
                unique=True,
            ),
        ),
    ]
