# Generated by Django 4.2.1 on 2024-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DatabaseConnections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectioninfo",
            name="used_in_orders_view",
            field=models.BooleanField(default=False),
        ),
    ]
