# Generated by Django 4.2.1 on 2024-07-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DatabaseConnections", "0004_connectioninfo_delete_databaseconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectioninfo",
            name="dbms",
            field=models.CharField(
                choices=[
                    ("postgres", "PostgreSQL"),
                    ("mssql", "Microsoft SQL Server"),
                    ("manifest", "Manifest"),
                ],
                default="mssql",
                max_length=50,
            ),
        ),
    ]
