# Generated by Django 4.2.1 on 2024-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DatabaseConnections", "0005_alter_connectioninfo_dbms"),
    ]

    operations = [
        migrations.AddField(
            model_name="connectioninfo",
            name="erp_system",
            field=models.CharField(
                choices=[
                    ("odoo", "ODOO"),
                    ("winkhaus", "Winkhaus"),
                    ("manifest", "Manifest"),
                ],
                default="winkhaus",
                max_length=20,
            ),
        ),
    ]
