# Generated by Django 4.2.1 on 2024-09-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DatabaseConnections", "0006_connectioninfo_erp_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectioninfo",
            name="erp_system",
            field=models.CharField(
                choices=[
                    ("odoo", "ODOO"),
                    ("winkhaus", "Winkhaus"),
                    ("manifest", "Manifest"),
                    ("5s_control", "5sControl"),
                ],
                default="winkhaus",
                max_length=20,
            ),
        ),
    ]
