# Generated by Django 4.1.4 on 2023-02-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="password",
            field=models.CharField(
                blank=True, default="admin", max_length=250, null=True
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="username",
            field=models.CharField(
                blank=True, default="admin", max_length=100, null=True
            ),
        ),
    ]
