# Generated by Django 4.2.1 on 2024-10-17 12:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "image_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, null=True)),
                ("download_status", models.BooleanField(default=False)),
                (
                    "used_in",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("orders_view", "Orders View"),
                            ("inventory", "Inventory"),
                        ],
                        default="dashboard",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Algorithm",
                "verbose_name_plural": "Algorithms",
                "db_table": "algorithm",
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ID must be a valid IP address",
                                regex="^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}$",
                            )
                        ],
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=250)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
                "db_table": "camera",
            },
        ),
        migrations.CreateModel(
            name="CameraAlgorithmLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm_name", models.CharField(max_length=150)),
                ("camera_ip", models.CharField(max_length=150)),
                ("stoped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "CameraAlgorithmLog",
                "verbose_name_plural": "CameraAlgorithmLogs",
                "db_table": "camera_algorithms_log",
            },
        ),
        migrations.CreateModel(
            name="ZoneCameras",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coords", models.JSONField(verbose_name="Zone coordinates")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "workplace",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Workplace in the system ERP",
                    ),
                ),
                (
                    "index_workplace",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Index workplace",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Date updated"),
                ),
                (
                    "approximate_duration",
                    models.IntegerField(
                        blank=True,
                        default=5,
                        null=True,
                        verbose_name="Preliminary operation duration in seconds",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Zone_cameras",
                        to="CameraAlgorithms.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Camera zone",
                "verbose_name_plural": "Camera zone",
                "db_table": "camera_zones",
            },
        ),
        migrations.CreateModel(
            name="CameraAlgorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("process_id", models.PositiveBigIntegerField(default=0)),
                (
                    "zones",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Id zones algorithm"
                    ),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CameraAlgorithms.algorithm",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CameraAlgorithms.camera",
                    ),
                ),
            ],
            options={
                "verbose_name": "CameraAlgorithm",
                "verbose_name_plural": "CameraAlgorithms",
                "db_table": "camera_algorithm",
            },
        ),
    ]
