# Generated by Django 4.2.1 on 2025-02-25 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Mailer", "0002_workingtimedaysofweek_alter_workingtime_days_of_week"),
        ("CameraAlgorithms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CameraAlgorithms.camera",
                    ),
                ),
                (
                    "working_time_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Mailer.workingtimedaysofweek",
                    ),
                ),
            ],
            options={
                "db_table": "camera_schedule",
            },
        ),
    ]
