# Generated by Django 4.1.4 on 2023-05-02 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cameraalgorithm",
            name="algorithm",
        ),
        migrations.RemoveField(
            model_name="cameraalgorithm",
            name="camera",
        ),
        migrations.DeleteModel(
            name="CameraAlgorithmLog",
        ),
        migrations.DeleteModel(
            name="Algorithm",
        ),
        migrations.DeleteModel(
            name="Camera",
        ),
        migrations.DeleteModel(
            name="CameraAlgorithm",
        ),
    ]
