# Generated by Django 4.2.1 on 2025-02-28 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0002_cameraschedule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cameraschedule",
            options={
                "verbose_name": "Camera Schedule",
                "verbose_name_plural": "Camera Schedule",
            },
        ),
    ]
