# Generated by Django 4.2.1 on 2023-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0002_zonecameras"),
    ]

    operations = [
        migrations.AddField(
            model_name="cameraalgorithm",
            name="zones",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Id zones algorithm"
            ),
        ),
    ]
