# Generated by Django 4.2.1 on 2023-09-21 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0004_zonecameras_index_workplace_zonecameras_workplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonecameras",
            name="camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Zone_cameras",
                to="CameraAlgorithms.camera",
            ),
        ),
    ]
