# Generated by Django 4.2.1 on 2023-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0006_algorithm_date_updated_algorithm_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="image_name",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
