# Generated by Django 4.2.1 on 2023-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0007_alter_algorithm_image_name_alter_algorithm_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="download_status",
            field=models.BooleanField(default=False),
        ),
    ]
