# Generated by Django 4.2.1 on 2023-09-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0008_algorithm_download_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="date_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
