# Generated by Django 4.2.1 on 2024-08-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0010_algorithm_used_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonecameras",
            name="workplace",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Workplace db Winkhaus",
            ),
        ),
    ]
