# Generated by Django 4.2.1 on 2024-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0011_alter_zonecameras_workplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonecameras",
            name="approximate_duration",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Preliminary duration of the operation",
            ),
        ),
    ]
