# Generated by Django 4.2.1 on 2024-08-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0012_zonecameras_approximate_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonecameras",
            name="approximate_duration",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Preliminary operation duration in seconds",
            ),
        ),
        migrations.AlterField(
            model_name="zonecameras",
            name="index_workplace",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Index workplace"
            ),
        ),
        migrations.AlterField(
            model_name="zonecameras",
            name="workplace",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Workplace in the system ERP",
            ),
        ),
    ]
