# Generated by Django 4.2.1 on 2024-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0013_alter_zonecameras_approximate_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonecameras",
            name="approximate_duration",
            field=models.IntegerField(
                blank=True,
                default=5,
                null=True,
                verbose_name="Preliminary operation duration in seconds",
            ),
        ),
    ]
