# Generated by Django 4.2.1 on 2024-09-11 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0014_alter_zonecameras_approximate_duration"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cameraalgorithm",
            table="camera_algorithm",
        ),
        migrations.AlterModelTable(
            name="cameraalgorithmlog",
            table="camera_algorithms_log",
        ),
    ]
