# Generated by Django 4.2.1 on 2024-09-11 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CameraAlgorithms", "0015_alter_cameraalgorithm_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="zonecameras",
            options={
                "verbose_name": "Camera zone",
                "verbose_name_plural": "Camera zone",
            },
        ),
        migrations.AlterModelTable(
            name="zonecameras",
            table="camera_zones",
        ),
    ]
