# Generated by Django 4.1.4 on 2023-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Locations", "0002_camera_password_camera_username"),
        ("Algorithms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="algorithms",
            old_name="is_active",
            new_name="is_available",
        ),
        migrations.AddField(
            model_name="algorithms",
            name="cameras",
            field=models.ManyToManyField(
                related_name="choose_camera", to="Locations.camera"
            ),
        ),
    ]
