# Generated by Django 4.1.4 on 2023-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Algorithms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraAlgorithmLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm_name", models.CharField(max_length=150)),
                ("camera_ip", models.CharField(max_length=150)),
                ("stoped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
