# Generated by Django 4.1.4 on 2023-02-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Algorithms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cameraalgorithm",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cameraalgorithm",
            name="process_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
