# Generated by Django 4.1.4 on 2023-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Algorithms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
