# Generated by Django 4.1.4 on 2023-05-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Algorithms", "0002_algorithm_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraalgorithm",
            name="process_id",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
