# Generated by Django 4.1.4 on 2023-02-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Algorithms", "0002_cameraalgorithm_is_active_cameraalgorithm_process_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraalgorithm",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
