# Generated by Django 4.1.4 on 2023-05-12 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Algorithms", "0003_alter_cameraalgorithm_process_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algorithm",
            options={"verbose_name": "Algorithm", "verbose_name_plural": "Algorithms"},
        ),
        migrations.AlterModelOptions(
            name="cameraalgorithm",
            options={
                "verbose_name": "CameraAlgorithm",
                "verbose_name_plural": "CameraAlgorithms",
            },
        ),
        migrations.AlterModelOptions(
            name="cameraalgorithmlog",
            options={
                "verbose_name": "CameraAlgorithmLog",
                "verbose_name_plural": "CameraAlgorithmLogs",
            },
        ),
        migrations.AlterModelTable(
            name="algorithm",
            table="algorithm",
        ),
        migrations.AlterModelTable(
            name="cameraalgorithm",
            table="cameraalgorithm",
        ),
        migrations.AlterModelTable(
            name="cameraalgorithmlog",
            table="cameraalgorithmslog",
        ),
    ]
