# Generated by Django 4.2.1 on 2024-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ReportsAI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtensionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_post", models.TextField()),
                ("text_comment", models.TextField()),
                ("link_author_comment", models.URLField()),
                ("about_user", models.TextField()),
                ("about_author", models.TextField()),
                ("user_company", models.CharField(max_length=255)),
                ("user_experience", models.CharField(max_length=255)),
                ("user_link", models.URLField()),
                ("user_name", models.CharField(max_length=255)),
                ("user_position", models.CharField(max_length=255)),
                ("extension_user", models.CharField(max_length=255)),
                ("ai_comments", models.TextField()),
                ("project_id", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="SocialPost",
        ),
    ]
