# Generated by Django 4.1.4 on 2023-04-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Locations", "0001_initial"),
        ("Employees", "0001_initial"),
        ("Cameras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateTimeField(auto_now_add=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                (
                    "image",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Image"
                    ),
                ),
                (
                    "name_file",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="name_file"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="action camera",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Cameras.camera",
                        verbose_name="NameCamera",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Location_users",
                        to="Locations.location",
                    ),
                ),
                (
                    "people",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="people_in_location",
                        to="Employees.staffcontroluser",
                    ),
                ),
            ],
            options={
                "verbose_name": "History",
                "verbose_name_plural": "History",
            },
        ),
    ]
