name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Connect to server and update repository
      run: |
        curl https://a992-134-17-26-206.eu.ngrok.io/
