name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Connect to server and update repository
      run: |
        echo "Process was started" 
        ssh server@7.tcp.eu.ngrok.io -p 14920 'cd reps/django/ && git pull'
        echo "Repository updated successfully."
