name: dev

on:
  push:
    branches: [development]

jobs:
  Build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: Build container
        run: docker build . -t 5scontrol/django:latest

      - name: Push container
        run: docker push 5scontrol/django:latest

      - name: Deploy
        run: curl 192.168.1.115:4545/deploy-pod?service=backend
