# Generated by Django 4.2.1 on 2023-06-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FiltrationOperationsTypeID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type_id", models.IntegerField(unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "filtration_operations",
            },
        ),
    ]
