# Generated by Django 4.2.1 on 2024-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FiltrationOperationsTypeID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "type_erp",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "filtration_operations",
            },
        ),
    ]
