# Generated by Django 4.2.1 on 2024-12-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newOrderView", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filtrationoperationstypeid",
            name="operation_type_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
