# Generated by Django 4.2.1 on 2024-08-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newOrderView", "0002_filtrationoperationstypeid_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filtrationoperationstypeid",
            name="operation_type_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
