# Generated by Django 4.2.1 on 2024-09-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newOrderView", "0003_alter_filtrationoperationstypeid_operation_type_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="filtrationoperationstypeid",
            name="type_erp",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
