# Generated by Django 4.1.4 on 2023-03-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camera",
            name="password",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="camera",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
