# Generated by Django 4.1.4 on 2023-05-04 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="camera",
            old_name="password",
            new_name="_password",
        ),
    ]
