# Generated by Django 4.1.4 on 2023-04-27 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camera",
            name="description",
        ),
    ]
