# Generated by Django 4.1.4 on 2023-05-12 07:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Cameras", "0003_rename__password_camera_password"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="camera",
            table="camera",
        ),
    ]
